title: Ten Percent Wild Music
email: ""
description: "A musical site made by a music producer, a wild creator, a reality flexer"
baseurl: ""
url: "https://tenpercentwildmusic.github.io"

theme: minima
